# Generated by Django 3.1.7 on 2021-04-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drzava',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontinent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=30, unique=True)),
                ('opis', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('drzavaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.drzava')),
            ],
        ),
        migrations.CreateModel(
            name='Recenzija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tekst', models.TextField()),
                ('korisnikId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.korisnik')),
                ('lokacijaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lokacija')),
            ],
        ),
        migrations.CreateModel(
            name='Ocjena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrijednost', models.IntegerField()),
                ('korisnikId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.korisnik')),
                ('lokacijaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.lokacija')),
            ],
        ),
        migrations.AddField(
            model_name='drzava',
            name='kontinentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.kontinent'),
        ),
    ]
