# Generated by Django 3.1.7 on 2021-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drzava',
            name='slika',
            field=models.ImageField(default='static/img/bosna.jpg', upload_to='drzave'),
        ),
    ]
