# Generated by Django 3.1.7 on 2021-05-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_drzava_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokacija',
            name='grad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='drzava',
            name='slika',
            field=models.ImageField(default='static/img/bosna.jpg', upload_to='static/drzave'),
        ),
    ]
