# Generated by Django 3.1.7 on 2021-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210531_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='drzava',
            name='brojLokacija',
            field=models.IntegerField(default=0),
        ),
    ]
