# Generated by Django 3.1.7 on 2021-05-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_drzava_brojlokacija'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokacija',
            name='glavna_slika',
            field=models.ImageField(default='static/img/bosna.jpg', upload_to='static/lokacije'),
        ),
    ]
