# Generated by Django 3.1.7 on 2021-05-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_lokacija_glavna_slika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lokacija',
            name='glavna_slika',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
    ]
