# Generated by Django 3.1.7 on 2021-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210531_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='lokacija',
            name='slika1',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika2',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika3',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika4',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika5',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika6',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika7',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
        migrations.AddField(
            model_name='lokacija',
            name='slika8',
            field=models.ImageField(default='static/img/travel.jpg', upload_to='static/lokacije'),
        ),
    ]
