# Generated by Django 3.1.7 on 2021-06-03 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0009_auto_20210602_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocjena',
            name='korisnikId',
        ),
        migrations.RemoveField(
            model_name='recenzija',
            name='korisnikId',
        ),
        migrations.AddField(
            model_name='ocjena',
            name='korisnik',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recenzija',
            name='korisnik',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
