# Generated by Django 3.1.7 on 2021-06-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20210603_1814'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Korisnik',
        ),
    ]
