# Generated by Django 3.1.7 on 2021-06-06 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_delete_korisnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzija',
            name='ocjena',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ocjena',
        ),
    ]
